### ISSUE TITLE
 error: field '_host' has incomplete type 'std::string' {aka 'std::__cxx11::basic_string<char>'}

### ISSUE THREAD

**Issue by MKontrol** [mobizt/ESP-Signer#2]
E:\Documents\Arduino\libraries\ESP-Signer-main\src\wcs\esp8266\ESP_Signer_HTTPClient.h:97:15: error: field '_host' has incomplete type 'std::string' {aka 'std::__cxx11::basic_string<char>'}
   97 |   std::string _host = "";
      |               ^~~~~

Error when compiling the files itself.

To Reproduce

Update to arduino core 3.0.0
Open any example from library
Compile
Expected behavior
Was compiling flawlessly previously in Arduino core 2.7.4

IDE and its version:

Arduino, 1.8.14
ESP8266 Arduino Core SDK version

3.0.0

**Comment by mobizt** [comment]
This is the changes in GCC form v4 to v10.2 issue.

It was fixed already, please update the library to [v1.0.6](https://github.com/mobizt/ESP-Signer/releases/tag/v1.0.6).
