### ISSUE TITLE
ENHANCEMENT

### ISSUE THREAD

**Issue by skobkars** [mobizt/ESP-Signer#4]
**Is your feature request related to a problem? Please describe.**
In my project I must use Adafruit Fork of SdFat library, but it conflicts with the the SdFat from greiman.

**Describe the solution you'd like**
Please add Adafruit Fork of SdFat support to your library.

**Describe alternatives you've considered**
1. SdFat is already activated and mounted for other purposes in my project, so it would be great if I could skip Sd initialization and just pass the already activated SdFat object to ESP-Signer

2. I could use Flash file system, but cannot have both SdFat and Flash FS as they define conflicting File classes.

3. Or PSRAM? But see below.

**Additional context**
I also tried disabling all file systems and just leave PSRAM parameters in FS_Config.h, but then I get these errors, so as I understand file system is a must:

```
ESP_Signer_TCP_Client.cpp:98:9: error: 'fs' has not been declared
         fs::File file = mbfs->getFlashFile();

...

ESP_Signer_TCP_Client.cpp:99:25: error: 'file' was not declared in this scope
         wcs->loadCACert(file, len);

...

ESP_Signer_TCP_Client.cpp:99:25: note: suggested alternative: 'pipe'
         wcs->loadCACert(file, len);
```

**Comment by mobizt** [comment]
I can't support that forked version that APIs are different from original and still used the same header files and definition `SD_FAT_VERSION` .

The forked version also conflicts with the ESP32 core library that used widely in all libraries.
https://github.com/espressif/arduino-esp32/blob/master/libraries/FS/src/FS.h
