### ISSUE TITLE
BUG - Misspelled file capitalization breaks include in PlatformIO

### ISSUE THREAD

**Issue by coledeck** [mobizt/ESP-Signer#6]
**Describe the bug**
ESP_Signer.h and GAuth_OAUth2_Client.cpp includes the file "auth/GAuth_OAuth2_Client.h"
However the file is actually named GAuth_OAUth2_Client.h
Note the capital U.
At least on PlatformIO, this causes compile to fail because it can't find the include.
**To Reproduce**
Try to compile example in PlatformIO (Note - using arduino-pico)

**Expected behavior**
Should compile the library correctly.

**Comment by mobizt** [comment]
Thanks, it fixed now.

**Comment by coledeck** [comment]
Thanks for quick response!
