### ISSUE TITLE
Guidance on how to use

### ISSUE THREAD

**Issue by jksemple** [mobizt/ESP-Signer#8]
This is a useful library and I was able to get the Basic example code running with my own Service Account details very quickly.  However, the example just demonstrates the refresh of Auth Tokens not their usage. I have struggled using it to build my own client to access Google Cloud Storage and Google Vision.  

The library instantiates a global Signer object, which I therefore presume is the intended means of access to the functionality.  However, the ESP_Signer class has access specifiers that prevent access to the TCP client (authClient.tcpClient) from outside.

Looking at your earlier work such as ESP-Google-Forms-Client the client class GFormsClass (picks up the authMan TCP Client and uses that to run the API but in that design the GAuthManager object grants explicit friend class access so it can bypass the protected and private access specifiers.

I have made it work by making my own client class inherit from ESP_Signer and by granting friend class access to my own class within GAuth_OAuth2_Client but I'm sure this is not how you intended it to be used.  Should I perhaps be using a different TCP client object and not try to obtain the one used by Signer itself?

It would be helpful to see an example of how to use ESP_Signer within the context of a simple API client as you intend it should work e.g. one that just uploads a GCS storage file.

Alternatively, it would be great to see ESP_Signer refactored into, say, your ESP-Google-Forms-Client however I appreciate you have moved on since that work.  I did try using your Firebase-ESP-Client but it won't compile for XIAO_ESP32S3 if I disable the bits I don't need such as OTA and Firestore.  It compiles fine for ESP32.

**Comment by mobizt** [comment]
If you have the problem with Firebase library, you should open the issue there with the details.

The following is the example code for using external basic Arduino Client with this library.

Note that, you cannot use SSL client e.g., WiFiClientSecure with this library.

```cpp
WiFiClient client;

SignerConfig config;

void tokenStatusCallback(TokenInfo info)
{
  if (info.status == esp_signer_token_status_error)
  {
    Signer.printf("Token info: type = %s, status = %s\n", Signer.getTokenType(info).c_str(), Signer.getTokenStatus(info).c_str());
    Signer.printf("Token error: %s\n", Signer.getTokenError(info).c_str());
  }
  else
  {
    Signer.printf("Token info: type = %s, status = %s\n", Signer.getTokenType(info).c_str(), Signer.getTokenStatus(info).c_str());
    if (info.status == esp_signer_token_status_ready)
      Signer.printf("Token: %s\n", Signer.accessToken().c_str());
  }
}

void networkConnection()
{

#if defined(ESP32) || defined(ESP8266)
  WiFi.setAutoReconnect(true);
#endif

#if defined(ARDUINO_RASPBERRY_PI_PICO_W)
  multi.addAP(WIFI_SSID, WIFI_PASSWORD);
  multi.run();
#else
  WiFi.begin(WIFI_SSID, WIFI_PASSWORD);
#endif

  Serial.print("Connecting to Wi-Fi");
  unsigned long ms = millis();
  while (WiFi.status() != WL_CONNECTED)
  {
    Serial.print(".");
    delay(300);
#if defined(ARDUINO_RASPBERRY_PI_PICO_W)
    if (millis() - ms > 10000)
      break;
#endif
  }
  Serial.println();
  Serial.print("Connected with IP: ");
  Serial.println(WiFi.localIP());
  Serial.println();
}

// Define the callback function to handle server status acknowledgement
void networkStatusRequestCallback()
{
  // Set the network status
  Signer.setNetworkStatus(WiFi.status() == WL_CONNECTED);
}

void setup()
{
  Serial.begin(115200);
  Serial.println();
  Serial.println();

  networkConnection();
  /* Assign the sevice account credentials and private key (required) */
  config.service_account.data.client_email = CLIENT_EMAIL;
  config.service_account.data.project_id = PROJECT_ID;
  config.service_account.data.private_key = PRIVATE_KEY;

  /* Expired period in seconds (optional). Default is 3600 sec.*/
  config.signer.expiredSeconds = 3600;

  /* Seconds to refresh the token before expired (optional). Default is 60 sec.*/
  config.signer.preRefreshSeconds = 60;

  config.token_status_callback = tokenStatusCallback;

  // https://developers.google.com/identity/protocols/oauth2/scopes
  config.signer.tokens.scope = "https://www.googleapis.com/auth/devstorage.full_control,https://www.googleapis.com/auth/cloud-platform";

  Signer.setExternalClient(&client, networkConnection, networkStatusRequestCallback);
  
  Signer.begin(&config);
}

void loop()
{
  // Check to status and also refresh the access token
  bool ready = Signer.tokenReady();
  if (ready)
  {

  }
}
```

**Comment by jksemple** [comment]
Perfect response and very fast too. You're a star.
