### ISSUE TITLE
MB_String appendNum not functioning correctly on Arduino UNO R4 WiFi

### ISSUE THREAD

**Issue by Known4225** [mobizt/ESP-Signer#9]
**Describe the bug**
When appendNum is called on an MB_String, the string "ld" or "lu" is appended instead of the actual number

**To Reproduce**
Make an MB_String and try to append a number to it on the UNO R4 WiFi

**Expected behavior**
The number (base 10 ascii) should be appended

**Screenshots**
![image](https://github.com/mobizt/ESP-Signer/assets/83723434/dd814d62-3eb4-4767-be37-4207eaf480e9)
I think there should be an extra "|| defined(ARDUINO_UNO_R4)" (not the real macro, i dont know what it is) here to check for the UNO, because I think it is assuming it's a 64-bit processor which it isn't and thus does not understand "%lld" and "%llu" in the 64 bit toStr functions.

**Additional context**
I fixed it by modifying the int64Str and uint64Str to "%ld" and "%lu" instead of "%lld" and "%llu". But I don't think it should be calling those functions anyway. I can't find the macro used to determine if the board is the UNO R4. It's also possible that there are other spots in the code where the UNO is assumed to have 64 bit architecture. This is the only problem I've run into that causes the library to fail for my purposes though.

**Comment by mobizt** [comment]
I'm sorry to tell you that this library does not support Arduino UNO R4 WiFi because of stack memory provided by its core is too low and not enough for BearSSL engine to work.

I will remove it from support devices in Readme.
